/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dischunksstoreservice_CONSTANTS_H
#define dischunksstoreservice_CONSTANTS_H

#include "dischunksstoreservice_types.h"

namespace DIS {

class dischunksstoreserviceConstants {
 public:
  dischunksstoreserviceConstants();

};

extern const dischunksstoreserviceConstants g_dischunksstoreservice_constants;

} // namespace

#endif
