/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dischunksstoreservice_constants.h"

namespace DIS {

const dischunksstoreserviceConstants g_dischunksstoreservice_constants;

dischunksstoreserviceConstants::dischunksstoreserviceConstants() {
}

} // namespace

