/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package crdhn.fsp.thrift.response;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TErrorCode implements org.apache.thrift.TEnum {
  EC_OK(0),
  EC_SYSTEM(1),
  EC_PARAM_ERROR(2),
  EC_FILE_NOT_FOUND(3),
  EC_CHUNK_NOT_FOUND(4),
  EC_CHUNK_EXISTED(5),
  EC_MISSING_CHUNK(6),
  EC_MONGODB_CONNECTOR_ERROR(20),
  EC_STEP_COUNTER_ERROR(21);

  private final int value;

  private TErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return EC_OK;
      case 1:
        return EC_SYSTEM;
      case 2:
        return EC_PARAM_ERROR;
      case 3:
        return EC_FILE_NOT_FOUND;
      case 4:
        return EC_CHUNK_NOT_FOUND;
      case 5:
        return EC_CHUNK_EXISTED;
      case 6:
        return EC_MISSING_CHUNK;
      case 20:
        return EC_MONGODB_CONNECTOR_ERROR;
      case 21:
        return EC_STEP_COUNTER_ERROR;
      default:
        return null;
    }
  }
}
